### ISSUE TITLE
Listed in FALLOUT 4 repository

### ISSUE THREAD

**Issue by Battlestar1965** [radj307/GrassFPS#2]
Hi,

this patcher is listed in the Fallout 4 repository, but is not working for Fallout 4.

Error message from Synthesis:

Compiling
No extra data to consider
("C:\Users\battl\AppData\Local\Temp\Synthesis\j1grn5sz.l1n\Git\0fdfqehr.ykh\Runner\GrassFPS"): "dotnet" "build \"GrassFPS.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "df4545b0b7100b3b3a29f2682a1f6748ca05615a"
Running
(""): "dotnet" "run --project \"C:\Users\battl\AppData\Local\Temp\Synthesis\j1grn5sz.l1n\Git\0fdfqehr.ykh\Runner\GrassFPS\GrassFPS.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"G:\Games\Fallout 4\Data\" --ExtraDataFolder \"G:\Modding Tools\Synthesis_FO4\Data\Fallout 4\GrassFPS\" --GameRelease Fallout4 --ModKey \"Test Group.esp\" --LoadOrderFilePath \"C:\Users\battl\AppData\Local\Temp\Synthesis\j1grn5sz.l1n\Workspace\Test Group\Plugins.txt\" --LoadOrderIncludesCreationClub --Localize --OutputPath \"C:\Users\battl\AppData\Local\Temp\Synthesis\j1grn5sz.l1n\Workspace\Test Group\1 - GrassFPS\Test Group.esp\" --PatcherName GrassFPS"
Mutagen version: 0.40
Mutagen sha: 2c78952371b3e1019cbe76584ebd9d755411c751
Synthesis version: 0.25.2
Synthesis sha: 91d27bc6d57170ba868d543164079edfd981b533
Newtonsoft version: 13.0.1+ae9fe44e1323e91bcbd185ca1a14099fba7c021f
run-patcher --DataFolderPath "G:\Games\Fallout 4\Data" --ExtraDataFolder "G:\Modding Tools\Synthesis_FO4\Data\Fallout 4\GrassFPS" --GameRelease Fallout4 --ModKey "Test Group.esp" --LoadOrderFilePath "C:\Users\battl\AppData\Local\Temp\Synthesis\j1grn5sz.l1n\Workspace\Test Group\Plugins.txt" --LoadOrderIncludesCreationClub --Localize --OutputPath "C:\Users\battl\AppData\Local\Temp\Synthesis\j1grn5sz.l1n\Workspace\Test Group\1 - GrassFPS\Test Group.esp" --PatcherName GrassFPS
**_System.ArgumentException: No applicable patchers for Fallout4_**
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 540
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 472
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 833
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 460
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 432

**Comment by radj307** [comment]
Removed from fallout 4 repository as of c5bda03497832a4bce77304c2ca2828c9bb37db3
